
[COMPATIBLITY]
	#Turns on Auto Compatibility for Modernity to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_MODERNITY_ITEMS = true
	#Turns on Auto Compatibility for Cyclic to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_CYCLIC_ITEMS = true
	#Turns on Auto Compatibility for Vampirism to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_VAMPIRIS_ITEMS = true
	#Turns on Auto Compatibility for PlantTech2 to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_PLANTTECH2_ITEMS = true
	#Turns on Auto Compatibility for Underwater Biome to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_UNDERWATERBIOME_ITEMS = true
	#Turns on Auto Compatibility for ILikeWood Mod to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_ILIKEWOOD_ITEMS = true
	#Turns on Auto Compatibility for Vanilla Tweaks to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_VANILLATWEAKS_ITEMS = true
	#Turns on Auto Compatibility for Unstable Tools to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_UNSTABLETOOLS_ITEMS = true
	#Turns on Auto Compatibility for Poly Ores to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_POLYORES_ITEMS = true
	#Turns on Auto Compatibility for Lycanites Mobs to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_LYCANITESMOBS_ITEMS = true
	#Turns on Auto Compatibility for Essential Features to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_ESSENTIALFEATURES_ITEMS = true
	#Turns on Auto Compatibility for Good Night Sleep to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_GOODNIGHTSLEEP_ITEMS = true
	#Turns on Auto Compatibility for Spartan Shields to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_SPARTANSHIELDS_ITEMS = true
	#Turns on Auto Compatibility for Extra Bows to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_EXTRABOWS_ITEMS = true
	#Turns on Auto Compatibility for C.O.M.B.A.T to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_COMBAT_ITEMS = true
	#Turns on Auto Compatibility for Botania to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_BOTANIA_ITEMS = true
	#Turns on Auto Compatibility for Tetra Mod to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_TETRA_ITEMS = true
	#Turns on Auto Compatibility for Vanilla Gear to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_VANILLA_ITEMS = true
	#Turns on Auto Compatibility for Statues to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_STATUES_ITEMS = true
	#Turns on Auto Compatibility for Long Fall Boots to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_LONGFALLBOOTS_ITEMS = true
	#Turns on Auto Compatibility for Extra Enrichments to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_EXTRAENRICHMENTS_ITEMS = true
	#Turns on Auto Compatibility for Project E to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_PROJECTE_ITEMS = true
	#Turns on Auto Compatibility for Druidcraft Mod to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_DRUIDCRAFT_ITEMS = true
	#Turns on Auto Compatibility for Compacted to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_COMPACTED_ITEMS = true
	#Turns on Auto Compatibility for Cloud Boots to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_CLOUDBOOTS_ITEMS = true
	#Turns on Auto Compatibility for The One Probe to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_THEONEPROBE_ITEMS = true
	#Turns on Auto Compatibility for Rediscovered to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_REDISCOVERED_ITEMS = true
	#Turns on Auto Compatibility for Patty's More Stuff to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_PATTYSMORESTUFF_ITEMS = true
	#Turns on Auto Compatibility for Gami's Mod to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_GAMISMOD_ITEMS = true
	#Turns on Auto Compatibility for Yoyos to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_YOYOS_ITEMS = true
	#Turns on Auto Compatibility for Skeleton Lamps to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_SKELETONLAMPS_ITEMS = true
	#Turns on Auto Compatibility for Patty's More Armor to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_PATTYSMOREARMOR_ITEMS = true
	#Turns on Auto Compatibility for TofuCraft to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_TOFUCRAFT_ITEMS = true
	#Turns on Auto Compatibility for Ray's Dongles to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_RAYSDONGLES_ITEMS = true
	#Turns on Auto Compatibility for Patty's More Tools to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_PATTYSMORETOOLS_ITEMS = true
	#Turns on Auto Compatibility for Gobber to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_GOBBER_ITEMS = true
	#Turns on Auto Compatibility for AlikeTools Mod to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_ALIKETOOLS_ITEMS = true
	#Turns on Auto Compatibility for Powder Power to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_POWDERPOWER_ITEMS = true
	#Turns on Auto Compatibility for Ores Above Diamonds to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_ORESABOVEDIAMONDS_ITEMS = true
	#Turns on Auto Compatibility for Solar Generation to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_SOLARGENERATION_ITEMS = true
	#Turns on Auto Compatibility for Useless Sword to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_USELESSSWORD_ITEMS = true
	#Turns on Auto Compatibility for Aquaculture to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_AQUACULTURE_ITEMS = true
	#Turns on Auto Compatibility for Better Animals Plus to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_BETTERANIMALSPLUS_ITEMS = true
	#Turns on Auto Compatibility for FunItems Mod to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_FUNITEMSMOD_ITEMS = true
	#Turns on Auto Compatibility for Mutant Beasts to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_MUTANTBEASTS_ITEMS = true
	#Turns on Auto Compatibility for Nethercraft to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_NETHERCRAFT_ITEMS = true
	#Turns on Auto Compatibility for Simple Dive Gear to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_SIMPLEDIVEGEAR_ITEMS = true
	#Turns on Auto Compatibility for Switch Bow to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_SWITCHBOW_ITEMS = true
	#Turns on Auto Compatibility for Wyrmroost to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_WYRMROOST_ITEMS = true
	#Turns on Auto Compatibility for LuckyOres to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_LUCKYORES_ITEMS = true
	#Turns on Auto Compatibility for Mubble to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_MUBBLE_ITEMS = true
	#Turns on Auto Compatibility for Wither Skelton Tweaks to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_WITHERSKELETONTWEAKS_ITEMS = true
	#Turns on Auto Compatibility for XercaMod to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_XERCA_ITEMS = true
	#Turns on Auto Compatibility for Minecolonies to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_MINECOLONIES_ITEMS = true
	#Turns on Auto Explorercraft for FunItems Mod to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_EXPLORERCRAFT_ITEMS = true
	#Turns on Auto Compatibility for Blue Power to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_BLUEPOWER_ITEMS = true
	#Turns on Auto Compatibility for Craft and Hunt Mod to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_CRAFTHUNT_ITEMS = true
	#Turns on Auto Compatibility for Musket Mod to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_MUSKETMOD_ITEMS = true
	#Turns on Auto Compatibility for Enigmatic Legacy to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_ENIGMATICLEGACY_ITEMS = true
	#Turns on Auto Compatibility for Easy Steel to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_EASYSTEEL_ITEMS = true
	#Turns on Auto Compatibility for Mystical World to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_MYSTICALWORLD_ITEMS = true
	#Turns on Auto Compatibility for GemsPlusPlus to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_GEMSPLUSPLUS_ITEMS = true
	#Turns on Auto Compatibility for Endergetic to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_ENDERGETIC_ITEMS = true
	#Turns on Auto Compatibility for Quark to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_QUARK_ITEMS = true
	#Turns on Auto Compatibility for Gaia Dimension to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_GAIADIMENSION_ITEMS = true
	#Turns on Auto Compatibility for More Progression to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_MOREPROGRESSION_ITEMS = true
	#Turns on Auto Compatibility for Farlanders to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_FARLANDERS_ITEMS = true
	#Turns on Auto Compatibility for Forbidden and Arcanus to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_FORBIDDENARCANUS_ITEMS = true
	#Turns on Auto Compatibility for Bountiful Baubles Mod to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_BOUNTIFULBAUBLES_ITEMS = true
	#Turns on Auto Compatibility for Restrictions to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_RESTRICTIONS_ITEMS = true
	#Turns on Auto Compatibility for Midnight items to get Mine and Slash stats. Turn off to configure yourself
	USE_COMPATIBILITY_ON_MIDNIGHT_ITEMS = true

