
#Entity
[Entity]

	#Sets the tick, ticks happen 20 times each sec, interval in which non-running AI tasks are rechecked. Vanilla default is 1, this mods suggested default is 4
	[Entity.Entity]
		#goalselectorrate
		#Range: 1 ~ 500
		goalselectorrate = 4

		#Whether to use a slower updated AI tempt goal, tempt is used e.g. for luring sheep with wheat. default = true
		[Entity.Entity.Entity]
			#optimizeTempt
			optimizeTempt = true

			#Whether to use a slower updated AI avoid entity goal, avoid is used e.g. for villagers avoiding zombies so it constantly searches for mobs in the area. default = true
			[Entity.Entity.Entity.Entity]
				#optimizeAvoid
				optimizeAvoid = true

				#Whether to use a modified/fixed HurtByTarget goal which is used to call other entities for help. default = true
				[Entity.Entity.Entity.Entity.Entity]
					#optimizeHurtByTarget
					optimizeHurtByTarget = true

					#Whether to use a slower updated AI Panic entity goal, panic is used for chickens/other animals running away e.g. on fire. default = true
					[Entity.Entity.Entity.Entity.Entity.Entity]
						#optimizePanic
						optimizePanic = true

						#Whether to use a slower updated AI Breed entity goal, breed is used for searching nearby similar animals and doesnt have to be checked that often. default = true
						[Entity.Entity.Entity.Entity.Entity.Entity.Entity]
							#optimizeBreed
							optimizeBreed = true

							#Whether to use a slower updated AI Fox find shelter goal, which causes too much load. default = true
							[Entity.Entity.Entity.Entity.Entity.Entity.Entity.Entity]
								#slowFindShelter
								slowFindShelter = true

