
[general]
	#Combine entries of the same type instead of showing each one individually.
	"Combine Entries" = true
	#Make outdated entries slowly move out of the screen instead of disappearing in place.
	"Move Out Of Screen" = true
	#Make outdated entry names slowly fade away instead of simply vanishing.
	"Fade Away" = true
	#Include experience orbs the player has collected as part of the list of entries.
	"Display Experience" = true
	#Amount of ticks each entry will be shown for. Set to 0 to only remove entries when space for new ones is needed.
	#Range: > 0
	"Display Time" = 80
	#Amount of ticks it takes for an entry to move out of the screen. Value cannot be larger than "Display Time".
	#Range: > 0
	"Move Time" = 20
	#Color of the entry name text.
	#Allowed Values: WHITE, ORANGE, MAGENTA, LIGHT_BLUE, YELLOW, LIME, PINK, GRAY, LIGHT_GRAY, CYAN, PURPLE, BLUE, BROWN, GREEN, RED, BLACK
	"Text Color" = "WHITE"
	#Maximum count number displayed. Setting this to 0 will prevent the count from being displayed at all.
	#Range: > 0
	"Maximum Amount" = 9999
	#Disable specific items or content from whole mods from showing. Enter as either "modid:item" or "modid".
	Blacklist = ["examplemod", "examplemod:exampleitem"]
	#Ignore rarity of items and always use color specified in "Text Color" instead.
	"Ignore Rarity" = false
	#Show a small sprite next to the name of each entry showing its contents.
	"Draw Sprites" = true

[display]
	#Scale of entries. A lower scale will make room for more rows to show. Works in tandem with "GUI Scale" option in "Video Settings".
	#Range: 1 ~ 24
	"Custom Scale" = 4
	#Offset on x-axis from screen border.
	#Range: > 0
	X-Offset = 8
	#Screen corner for entry list to be drawn in.
	#Allowed Values: TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT
	"Screen Corner" = "BOTTOM_RIGHT"
	#Percentage of relative screen height entries are allowed to fill at max.
	#Range: 0.0 ~ 1.0
	"Maximum Height" = 0.5
	#Offset on y-axis from screen border.
	#Range: > 0
	Y-Offset = 150

